services:
  - type: web
    name: inventory-app
    env: python
    buildCommand:  "pip install -r requirements.txt"
    startCommand: "./manage.py migrate && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory_app
          property: connectionString
