# Generated by Django 5.1.4 on 2025-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('borrowed', '貸出中'), ('returned', '返却済み')], default='borrowed', max_length=20),
        ),
    ]
