# Generated by Django 5.1.4 on 2025-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
