# Generated by Django 5.1.4 on 2025-06-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_rental_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default='2025-06-11'),
            preserve_default=False,
        ),
    ]
