# Generated by Django 5.1.4 on 2025-06-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateField(),
        ),
    ]
