# Generated by Django 5.1.4 on 2025-06-13 06:06

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_rental_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=inventory.models.default_rental_date),
        ),
    ]
